I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "lib/windows-i686/script.rpyc", line 184, in script
  File "C:\Program Files\Renpy\renpy\ast.py", line 584, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Program Files\Renpy\renpy\ast.py", line 501, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'b' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
L'Ordre du Lys 1.0
