I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name u'start' is defined twice, at game/example.rpy:178 and game/script.rpy:178.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Documents\Isart_Docs\GD2\VN\Projet\RenPy\renpy-6.99.10-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\Documents\Isart_Docs\GD2\VN\Projet\RenPy\renpy-6.99.10-sdk\renpy\main.py", line 354, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "D:\Documents\Isart_Docs\GD2\VN\Projet\RenPy\renpy-6.99.10-sdk\renpy\script.py", line 259, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "D:\Documents\Isart_Docs\GD2\VN\Projet\RenPy\renpy-6.99.10-sdk\renpy\script.py", line 738, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "D:\Documents\Isart_Docs\GD2\VN\Projet\RenPy\renpy-6.99.10-sdk\renpy\script.py", line 414, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name u'start' is defined twice, at game/example.rpy:178 and game/script.rpy:178.

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
 
