I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 229, in script
    Gaston "Je sais que c'est difficile pour toi. Encore une fois je suis vraiment désolé."
Exception: Sayer 'Gaston' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 229, in script
    Gaston "Je sais que c'est difficile pour toi. Encore une fois je suis vraiment désolé."
  File "D:\Documents\Isart_Docs\GD2\VN\Projet\RenPy\renpy-6.99.10-sdk\renpy\ast.py", line 584, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Documents\Isart_Docs\GD2\VN\Projet\RenPy\renpy-6.99.10-sdk\renpy\ast.py", line 501, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Gaston' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
Renpy Imagebuttons GUI Sample 1.0
